### ISSUE TITLE
in `exit': no implicit conversion from nil to integer (TypeError)

### ISSUE THREAD

**Issue by m8ram** [solarkennedy/puppet-on-openwrt#3]
After registering the puppet agent is generated a lot of output ending in:

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not find default node or by name with 'openwrt.lan, openwrt, OpenWrt.lan, OpenWrt' on node openwrt.lan
Notice: Using cached catalog
Error: Could not retrieve catalog; skipping run
/usr/lib/ruby/1.9/puppet/agent.rb:89:in `exit': no implicit conversion from nil to integer (TypeError)
    from /usr/lib/ruby/1.9/puppet/agent.rb:89:in `block in run_in_fork'
    from /usr/lib/ruby/1.9/puppet/agent.rb:86:in `fork'
    from /usr/lib/ruby/1.9/puppet/agent.rb:86:in `run_in_fork'
    from /usr/lib/ruby/1.9/puppet/agent.rb:41:in `block in run'
    from /usr/lib/ruby/1.9/puppet/application.rb:179:in `call'
    from /usr/lib/ruby/1.9/puppet/application.rb:179:in `controlled_run'
    from /usr/lib/ruby/1.9/puppet/agent.rb:39:in `run'
    from /usr/lib/ruby/1.9/puppet/daemon.rb:205:in `block in run_event_loop'
    from /usr/lib/ruby/1.9/puppet/daemon.rb:167:in `loop'
    from /usr/lib/ruby/1.9/puppet/daemon.rb:167:in `run_event_loop'
    from /usr/lib/ruby/1.9/puppet/daemon.rb:145:in `start'
    from /usr/lib/ruby/1.9/puppet/application/agent.rb:357:in `main'
    from /usr/lib/ruby/1.9/puppet/application/agent.rb:313:in `run_command'
    from /usr/lib/ruby/1.9/puppet/application.rb:364:in `block (2 levels) in run'
    from /usr/lib/ruby/1.9/puppet/application.rb:456:in `plugin_hook'
    from /usr/lib/ruby/1.9/puppet/application.rb:364:in `block in run'
    from /usr/lib/ruby/1.9/puppet/util.rb:504:in `exit_on_fail'
    from /usr/lib/ruby/1.9/puppet/application.rb:364:in `run'
    from /usr/lib/ruby/1.9/puppet/util/command_line.rb:132:in `run'
    from /usr/lib/ruby/1.9/puppet/util/command_line.rb:86:in `execute'
    from /usr/bin/puppet:4:in `<main>'
^CNotice: Caught INT; calling stop
root@OpenWrt:~# 
```

I had not configured any recipe for openwrt so it is normal that it is unabe to retrieve a catalog at this point.  But it should not generate a TypeError.

Regards

Bram

**Comment by solarkennedy** [comment]
Probably this? 
https://projects.puppetlabs.com/issues/21935
